import { uid, baseObject } from "./constants.js";

const W = 1080, H = 1920;
const STUB = { width: W, height: H };

export const VIDEO_TEMPLATES = [
  {
    id: "video-fintech-fast",
    name: "⚡ Fast App Launch (FinTech)",
    tagline: "3 scenes · 9.0s · Upbeat Tech beat · Tilted device & balance cards",
    category: "Finance",
    swatch: "linear-gradient(135deg, #0B1220, #133E2B)",
    soundtrack: { id: "upbeat", title: "Upbeat Tech", volume: 0.85, customUrl: null },
    scenes: [
      {
        name: "Scene 1 — Meet FlowPay",
        duration: 3.0,
        transition: "slide",
        bg: { type: "linear", color1: "#0B1220", color2: "#142A22", angle: 135 },
        objects: [
          {
            type: "badge",
            x: 80, y: 120, width: 260, height: 50,
            text: "⚡ NEXT-GEN BANKING",
            fill: "rgba(41,211,152,0.14)", stroke: "rgba(41,211,152,0.4)", strokeWidth: 1,
            icon: "bolt", iconColor: "#29D398", textColor: "#29D398",
            videoEntrance: "fade", videoDelay: 0.1, videoDuration: 0.5,
          },
          {
            type: "text",
            x: 80, y: 190, width: 920, height: 160,
            text: "Smarter money.\nZero fees.",
            fontSize: 105, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.2, videoDuration: 0.6,
          },
          {
            type: "text",
            x: 80, y: 380, width: 900, height: 90,
            text: "Manage, invest, and send money globally with instant zero-fee settlement.",
            fontSize: 34, fontWeight: 400, fill: "rgba(255,255,255,0.7)",
            videoEntrance: "fade", videoDelay: 0.4, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 200, y: 560, width: 680, height: 1390,
            rotation: -8, tiltX: -10, tiltY: 14,
            videoEntrance: "spring-pop", videoDelay: 0.25, videoDuration: 0.8,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 540, y: 880, width: 440, height: 135,
            title: "+$1,420.50 Received",
            subtitle: "Instant transfer from Liam (Zero fee)",
            icon: "check", iconColor: "#29D398", iconBg: "rgba(41,211,152,0.2)",
            badgeText: "JUST NOW",
            videoEntrance: "tilt-in", videoDelay: 0.6, videoDuration: 0.6,
            videoLoop: "pulse",
          },
        ],
      },
      {
        name: "Scene 2 — Bank Grade Security",
        duration: 3.0,
        transition: "fade",
        bg: { type: "linear", color1: "#0F1A24", color2: "#0A2928", angle: 120 },
        objects: [
          {
            type: "badge",
            x: 80, y: 120, width: 280, height: 50,
            text: "🔒 BANK-GRADE TRUST",
            fill: "rgba(255,255,255,0.12)", stroke: "rgba(255,255,255,0.25)",
            icon: "shield", iconColor: "#29D398", textColor: "#ffffff",
            videoEntrance: "fade", videoDelay: 0.1, videoDuration: 0.4,
          },
          {
            type: "text",
            x: 80, y: 190, width: 920, height: 150,
            text: "Your security is\nour obsession.",
            fontSize: 98, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.2, videoDuration: 0.6,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 100, y: 520, width: 620, height: 1270,
            rotation: 6, tiltX: 8, tiltY: -10,
            videoEntrance: "spring-pop", videoDelay: 0.3, videoDuration: 0.8,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 520, y: 640, width: 480, height: 130,
            title: "256-bit AES Encryption",
            subtitle: "Biometric authentication & live fraud shield.",
            icon: "lock", iconColor: "#29D398", iconBg: "rgba(41,211,152,0.2)",
            videoEntrance: "slide-up", videoDelay: 0.5, videoDuration: 0.5,
          },
          {
            type: "card",
            x: 520, y: 820, width: 480, height: 130,
            title: "99.99% Uptime SLA",
            subtitle: "Multi-region redundant cloud cluster.",
            icon: "chart", iconColor: "#5B8CFF", iconBg: "rgba(91,140,255,0.2)",
            videoEntrance: "slide-up", videoDelay: 0.7, videoDuration: 0.5,
          },
        ],
      },
      {
        name: "Scene 3 — Download & Rating",
        duration: 3.0,
        transition: "zoom",
        bg: { type: "linear", color1: "#0B1220", color2: "#194D3B", angle: 135 },
        objects: [
          {
            type: "text",
            x: 80, y: 160, width: 920, height: 160,
            text: "Join 2M+ users\ngrowing today.",
            fontSize: 105, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.15, videoDuration: 0.6,
          },
          {
            type: "rating",
            x: 80, y: 400, width: 480, height: 120,
            score: "4.9", countText: "140K+ 5-Star Reviews", categoryText: "🏆 Editor's Choice 2026",
            videoEntrance: "tilt-in", videoDelay: 0.35, videoDuration: 0.7,
            videoLoop: "pulse",
          },
          {
            type: "device",
            style: "phone-notch",
            x: 230, y: 620, width: 620, height: 1270,
            rotation: 0, tiltX: 0, tiltY: 0,
            videoEntrance: "zoom-in", videoDelay: 0.45, videoDuration: 0.7,
            videoLoop: "float",
          },
          {
            type: "store_badge",
            platform: "play",
            x: 80, y: 1620, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.7, videoDuration: 0.5,
          },
          {
            type: "store_badge",
            platform: "appstore",
            x: 390, y: 1620, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.8, videoDuration: 0.5,
          },
        ],
      },
    ],
  },
  {
    id: "video-fitness-pulse",
    name: "🔥 High-Energy Action (Fitness)",
    tagline: "3 scenes · 9.0s · Energetic Pulse beat · Bold neon accents",
    category: "Fitness",
    swatch: "linear-gradient(135deg, #0F2027, #203A43, #2C5364)",
    soundtrack: { id: "pulse", title: "Energetic Pulse", volume: 0.85, customUrl: null },
    scenes: [
      {
        name: "Scene 1 — High Energy Intro",
        duration: 3.0,
        transition: "slide",
        bg: { type: "linear", color1: "#0F2027", color2: "#203A43", angle: 120 },
        objects: [
          {
            type: "badge",
            x: 80, y: 120, width: 250, height: 50,
            text: "⚡ LIVE WORKOUTS",
            fill: "rgba(166,255,0,0.15)", stroke: "#A6FF00", strokeWidth: 1,
            icon: "flame", iconColor: "#A6FF00", textColor: "#A6FF00",
            videoEntrance: "fade", videoDelay: 0.1, videoDuration: 0.4,
          },
          {
            type: "text",
            x: 80, y: 190, width: 920, height: 160,
            text: "Crush goals.\nEvery day.",
            fontSize: 110, fontWeight: 700, fill: "#A6FF00",
            videoEntrance: "slide-down", videoDelay: 0.15, videoDuration: 0.6,
          },
          {
            type: "text",
            x: 80, y: 390, width: 900, height: 80,
            text: "Adaptive AI training plans customized to your heart rate and endurance.",
            fontSize: 34, fontWeight: 400, fill: "#ffffff",
            videoEntrance: "fade", videoDelay: 0.35, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 180, y: 560, width: 720, height: 1470,
            rotation: -6, tiltX: -8, tiltY: 12,
            videoEntrance: "spring-pop", videoDelay: 0.25, videoDuration: 0.7,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 520, y: 780, width: 460, height: 130,
            title: "🔥 840 Calories Burned",
            subtitle: "HIIT Intensity · Zone 4 Heart Rate",
            icon: "bolt", iconColor: "#A6FF00", iconBg: "rgba(166,255,0,0.2)",
            videoEntrance: "tilt-in", videoDelay: 0.5, videoDuration: 0.6,
            videoLoop: "pulse",
          },
        ],
      },
      {
        name: "Scene 2 — Real-time Analytics",
        duration: 3.0,
        transition: "slide",
        bg: { type: "linear", color1: "#1B2838", color2: "#16202C", angle: 140 },
        objects: [
          {
            type: "text",
            x: 80, y: 150, width: 920, height: 150,
            text: "Precision stats\nat a glance.",
            fontSize: 100, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.1, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 80, y: 480, width: 640, height: 1310,
            rotation: 8, tiltX: 10, tiltY: -12,
            videoEntrance: "spring-pop", videoDelay: 0.3, videoDuration: 0.7,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 500, y: 640, width: 500, height: 130,
            title: "14-Day Streak Alive!",
            subtitle: "Top 5% performer in your region.",
            icon: "trophy", iconColor: "#F5A623", iconBg: "rgba(245,166,35,0.2)",
            videoEntrance: "tilt-in", videoDelay: 0.45, videoDuration: 0.6,
          },
          {
            type: "card",
            x: 500, y: 820, width: 500, height: 130,
            title: "Apple Watch & WearOS",
            subtitle: "Instant auto-detection on your wrist.",
            icon: "headphones", iconColor: "#A6FF00", iconBg: "rgba(166,255,0,0.2)",
            videoEntrance: "tilt-in", videoDelay: 0.65, videoDuration: 0.6,
          },
        ],
      },
      {
        name: "Scene 3 — Download CTA",
        duration: 3.0,
        transition: "fade",
        bg: { type: "linear", color1: "#0F2027", color2: "#2C5364", angle: 120 },
        objects: [
          {
            type: "text",
            x: 80, y: 180, width: 920, height: 150,
            text: "Start your streak.\n100% Free.",
            fontSize: 105, fontWeight: 700, fill: "#A6FF00",
            videoEntrance: "slide-up", videoDelay: 0.15, videoDuration: 0.6,
          },
          {
            type: "rating",
            x: 80, y: 440, width: 500, height: 125,
            score: "4.9", countText: "85,000+ Athletes", categoryText: "★ #1 Health & Fitness App",
            videoEntrance: "spring-pop", videoDelay: 0.35, videoDuration: 0.7,
            videoLoop: "pulse",
          },
          {
            type: "store_badge",
            platform: "play",
            x: 80, y: 640, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.6, videoDuration: 0.5,
          },
          {
            type: "store_badge",
            platform: "appstore",
            x: 390, y: 640, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.7, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 200, y: 800, width: 680, height: 1390,
            videoEntrance: "zoom-in", videoDelay: 0.5, videoDuration: 0.8,
            videoLoop: "float",
          },
        ],
      },
    ],
  },
  {
    id: "video-ai-assistant",
    name: "✨ AI Next-Gen (Tech & Copilot)",
    tagline: "3 scenes · 9.0s · Lo-Fi Chill beat · Glowing futuristic cards",
    category: "AI & Productivity",
    swatch: "linear-gradient(135deg, #100E2E, #28154D, #491B6D)",
    soundtrack: { id: "chill", title: "Chill Lo-Fi", volume: 0.85, customUrl: null },
    scenes: [
      {
        name: "Scene 1 — AI Introduction",
        duration: 3.0,
        transition: "fade",
        bg: { type: "linear", color1: "#0C0A1E", color2: "#2A1448", angle: 135 },
        objects: [
          {
            type: "badge",
            x: 80, y: 120, width: 260, height: 50,
            text: "✨ POWERED BY GPT-5",
            fill: "rgba(124,92,255,0.2)", stroke: "#7C5CFF", strokeWidth: 1,
            icon: "sparkles", iconColor: "#7C5CFF", textColor: "#E0D7FF",
            videoEntrance: "fade", videoDelay: 0.1, videoDuration: 0.5,
          },
          {
            type: "text",
            x: 80, y: 190, width: 920, height: 160,
            text: "Your personal\nsuper-intelligence.",
            fontSize: 105, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.2, videoDuration: 0.6,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 180, y: 560, width: 720, height: 1470,
            rotation: -8, tiltX: -10, tiltY: 14,
            videoEntrance: "spring-pop", videoDelay: 0.3, videoDuration: 0.8,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 520, y: 840, width: 480, height: 135,
            title: "Instant Code & Writing",
            subtitle: "Summarize, draft emails, and debug with one prompt.",
            icon: "sparkles", iconColor: "#7C5CFF", iconBg: "rgba(124,92,255,0.25)",
            badgeText: "AI 2.0",
            videoEntrance: "tilt-in", videoDelay: 0.6, videoDuration: 0.6,
            videoLoop: "pulse",
          },
        ],
      },
      {
        name: "Scene 2 — Voice & Realtime",
        duration: 3.0,
        transition: "slide",
        bg: { type: "linear", color1: "#140D2F", color2: "#381559", angle: 120 },
        objects: [
          {
            type: "text",
            x: 80, y: 160, width: 920, height: 150,
            text: "Natural voice,\ninstant answers.",
            fontSize: 100, fontWeight: 700, fill: "#ffffff",
            videoEntrance: "slide-up", videoDelay: 0.1, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 80, y: 500, width: 640, height: 1310,
            rotation: 6, tiltX: 8, tiltY: -10,
            videoEntrance: "spring-pop", videoDelay: 0.25, videoDuration: 0.7,
            videoLoop: "float",
          },
          {
            type: "card",
            x: 500, y: 680, width: 500, height: 130,
            title: "Sub-50ms Latency",
            subtitle: "Human-speed fluid conversational voice model.",
            icon: "bolt", iconColor: "#29D398", iconBg: "rgba(41,211,152,0.2)",
            videoEntrance: "tilt-in", videoDelay: 0.45, videoDuration: 0.6,
          },
          {
            type: "card",
            x: 500, y: 860, width: 500, height: 130,
            title: "Private & Encrypted",
            subtitle: "Zero data training. Your thoughts stay yours.",
            icon: "shield", iconColor: "#7C5CFF", iconBg: "rgba(124,92,255,0.2)",
            videoEntrance: "tilt-in", videoDelay: 0.65, videoDuration: 0.6,
          },
        ],
      },
      {
        name: "Scene 3 — Download",
        duration: 3.0,
        transition: "zoom",
        bg: { type: "linear", color1: "#0C0A1E", color2: "#2A1448", angle: 135 },
        objects: [
          {
            type: "text",
            x: 80, y: 180, width: 920, height: 150,
            text: "Experience the\nfuture today.",
            fontSize: 105, fontWeight: 700, fill: "#E0D7FF",
            videoEntrance: "slide-up", videoDelay: 0.15, videoDuration: 0.6,
          },
          {
            type: "rating",
            x: 80, y: 440, width: 500, height: 125,
            score: "5.0", countText: "98,000+ Happy Users", categoryText: "★ Top Productivity App 2026",
            videoEntrance: "spring-pop", videoDelay: 0.35, videoDuration: 0.7,
            videoLoop: "pulse",
          },
          {
            type: "store_badge",
            platform: "play",
            x: 80, y: 640, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.6, videoDuration: 0.5,
          },
          {
            type: "store_badge",
            platform: "appstore",
            x: 390, y: 640, width: 280, height: 80,
            videoEntrance: "slide-up", videoDelay: 0.7, videoDuration: 0.5,
          },
          {
            type: "device",
            style: "phone-notch",
            x: 220, y: 820, width: 640, height: 1310,
            videoEntrance: "zoom-in", videoDelay: 0.5, videoDuration: 0.8,
            videoLoop: "float",
          },
        ],
      },
    ],
  },
];

export function buildVideoTemplateProject(templateId) {
  const t = VIDEO_TEMPLATES.find((v) => v.id === templateId);
  if (!t) return null;

  const canvases = t.scenes.map((s, i) => {
    const objects = s.objects.map((obj) => baseObject(obj, STUB));
    return {
      id: uid("scr"),
      name: s.name,
      width: W,
      height: H,
      background: s.bg,
      videoDuration: s.duration || 3.0,
      videoTransition: s.transition || "slide",
      objects,
    };
  });

  return {
    name: t.name.replace(/^[^\s]+\s+/, ""), // strip leading emoji
    canvases,
    sharedObjects: [],
    connectBackground: false,
    globalBackground: canvases[0].background,
    soundtrack: t.soundtrack,
  };
}
